#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

# Run ESLint, Prettier, and TypeScript checks
npm run lint:fix && npm run format:write && npm run type-check && git add .

# Alternative using Biome (uncomment to use Biome instead)
# npm run biome:format && npm run type-check && git add .